### ISSUE TITLE
Problem 5 gives compile error

### ISSUE THREAD

**Issue by delyandamyanov** [Team-Project-SoftUni-2018/programming-fundamentals#3]
### Expected 
Problem 5's logic is okay and should give 100/100

###Actual
Gives compile error

Suggestion fix:
Variable "currHealth" should be changed to "currentHealth", line 16;
Variable "maxHealth" should be changed to "maximumHealth", line 18;
Variable "currEnergy" should be changed to "currentEnergy", line 20;
Variable "maxEnergy" should be changed to "maximumEnergy", line 22;

**Comment by DarkniaTristitia** [comment]
Fixed
